// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcBandas.Models;

namespace MvcBandas.Migrations
{
    [DbContext(typeof(MvcBandasContext))]
    [Migration("20190626042653_modelo_concierto")]
    partial class modelo_concierto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcBandas.Models.Banda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnioFormacion");

                    b.Property<DateTime>("FechaRegistro");

                    b.Property<string>("Genero")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<int>("NumeroIntegrantes");

                    b.Property<string>("Vocalistas")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Banda");
                });

            modelBuilder.Entity("MvcBandas.Models.Concierto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BandaId");

                    b.Property<DateTime>("Fecha");

                    b.Property<string>("Lugar")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BandaId");

                    b.ToTable("Concierto");
                });

            modelBuilder.Entity("MvcBandas.Models.Concierto", b =>
                {
                    b.HasOne("MvcBandas.Models.Banda", "Banda")
                        .WithMany()
                        .HasForeignKey("BandaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
